# Generated by Django 4.1.7 on 2023-03-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_doctor_charges_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancle_reason',
            field=models.TextField(default=''),
        ),
    ]
